version: "3.8"

# web services
services:
   django:
      build: .
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      volumes: 
         - .:/usr/src/app
      ports:
         - "8000:8000"
      depends_on:
         - pgdb
   pgdb:
      image: postgres
      container_name: pgdb
      restart: always
      environment:
         POSTGRES_DB: postgres  # djangoec2
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: p05tgr35.
      volumes:
         - pgdata:/var/lib/postgresql/data/

# volumes - persistent data (database)
volumes:
   pgdata:
